# Generated by Django 5.0.7 on 2024-08-08 04:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_snippet',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
