# Generated by Django 5.1 on 2024-08-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_auth_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
